version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: sentryx-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./visualization/grafana-data:/data
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - sentryx_net

  grafana:
    image: grafana/grafana:latest
    container_name: sentryx-grafana
    volumes:
      - ./visualization/grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - sentryx_net

  csv_exporter:
    build: 
      context: ./visualization
      dockerfile: Dockerfile
    container_name: sentryx-csv-exporter
    volumes:
      - ./visualization/grafana-data:/csv-data
    ports:
      - "9001:8000"
    restart: unless-stopped
    networks:
      - sentryx_net

  n8n:
    image: n8nio/n8n:latest
    container_name: sentryx-n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - sentryx_net

networks:
  sentryx_net:
    driver: bridge

volumes:
  n8n_data: