global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'csv_data'
    static_configs:
      - targets: ['csv_exporter:8000']