name: Snyk Security Scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  snyk_scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Installs your Python packages from requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      # Step 4: Sets up the Snyk CLI
      - name: Set up Snyk
        uses: snyk/actions/setup@master
      
      # Step 5: Runs the Snyk scan (now that packages are installed)
      - name: Run Snyk to check for vulnerabilities
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}